apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ $.Values.global.appname }}
    name: keycloak
    {{- range $label := $.Values.global.labels }}
    {{ $label.key }} : {{ tpl $label.value $ }}
    {{- end}}
  name: keycloak
spec:
  to:
    kind: Service
    name: keycloak
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge