kind: Service
apiVersion: v1
metadata:
  labels:
    app: {{ $.Values.global.appname }}
    name: keycloak
    {{- range $label := $.Values.global.labels }}
    {{ $label.key }} : {{ tpl $label.value $ }}
    {{- end}}
  name: keycloak
spec:
  selector:
    deploymentConfig: keycloak
  ports:
  - port: 8080
    targetPort: 8080